export const Action_List_Github_Repository = 'Action_Github_Repository'
export const Action_List_Github_Author = 'Action_Github_Author'
export const Action_List_Article_Detail = 'Action_List_Article_Detail'
export const Action_List_Article_Author = 'Action_List_Article_Author'
export const Action_List_Article_Tag = 'Action_List_Article_Tag'
export const Action_Channel_Type_Article = 'Action_Channel_Type_Article'
export const Action_Channel_Type_Github = 'Action_Channel_Type_Github'
export const Action_Channel_Type_Grammar = 'Action_Channel_Type_Grammar'
export const Action_Channel_Type_Word = 'Action_Channel_Type_Word'

export const Action_Display_List_Article = 'Action_Display_List_Article'
export const Action_Display_List_Github = 'Action_Display_List_Github'

export const Action_Filter_List_Article_Confirm = 'Action_Filter_List_Article_Confirm'
export const Action_Filter_List_Github_Confirm = 'Action_Filter_List_Github_Confirm'