export let Action_List_Github_Repository = 'Action_Github_Repository'
export let Action_List_Github_Author = 'Action_Github_Author'
export let Action_List_Article_Detail = 'Action_List_Article_Detail'
export let Action_List_Article_Author = 'Action_List_Article_Author'
export let Action_List_Article_Tag = 'Action_List_Article_Tag'
export let Action_Channel_Type_Article = 'Action_Channel_Type_Article'
export let Action_Channel_Type_Github = 'Action_Channel_Type_Github'
export let Action_Channel_Type_Grammar = 'Action_Channel_Type_Grammar'
export let Action_Channel_Type_Word = 'Action_Channel_Type_Word'

export let Action_Display_List_Article = 'Action_Display_List_Article'
export let Action_Display_List_Github = 'Action_Display_List_Github'